export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_CHANGE_PATH = 'SRT_CHANGE_PATH';
export const SET_ARTICLES = 'SET_ARTICLES';
export const SELECT_ARTICLE = 'SELECT_ARTICLE';

export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR'
export const SET_DIFERENT_PASSWORD = 'SET_DIFERENT_PASSWORD'


export const SET_COMMENTS = 'SET_COMMENTS'
export const NEW_COMMENT = 'NEW_COMMENT'

